### ISSUE TITLE
Image not hashlocked

### ISSUE THREAD

**Issue by daurnimator** [infro-io/comment-diffs-action#1]
The docker image referenced at https://github.com/infro-io/comment-diffs-action/blob/db395c6537ddf0e5cf78d989d668581a9b4e394d/action.yml#L18 is not hash locked, meaning that whatever is pushed to that docker repo will be run the the permissions and credentials passed in.

Please use a hashlocked docker image reference so that the action in this repository cannot change out from underneath the user.

**Comment by colethienes** [comment]
Done!

**Comment by daurnimator** [comment]
FYI you might want to use something like renovate to keep it up to date: https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
